### ISSUE TITLE
Error with openlayers 5.0.3

### ISSUE THREAD

**Issue by quangtt2016** [sakitam-fdd/wind-layer#25]
When using Windlayer with openlayers 5.0.3, error occured.
![image](https://user-images.githubusercontent.com/20198693/57132701-990b8080-6dca-11e9-9ddb-29f58b2b82e1.png)

It run OK with openlayers 4.6.5.

**Comment by quangtt2016** [comment]
In Windy.js -> appendTo(map):
    **_this.getSource().projection_ = this._getProjectionCode();_**
Instead of projection code, I try to assign projection.
   **_this.getSource().projection_ = this._getProjection();_**
...
----------
**_**_proto._getProjectionCode = function _getProjectionCode() {
      var code = '';
      var map = this.getMap();

      if (map) {
        code = map.getView() && map.getView().getProjection().getCode();
      } else {
        code = 'EPSG:3857';
      }

      return code;
    };**_**
-------------
It works OK now with both version ol 4.6.5 & 5.0.3.
[windLayer.zip](https://github.com/sakitam-fdd/wind-layer/files/3143930/windLayer.zip)

**Comment by sakitam-fdd** [comment]
@quangtt2016 Hi,on this issue, you can see that the ol upgrade [log](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#v500) itself is not forward compatible. The upgrade of ol5 is planned, but we can see the upgrade plan of [ol6](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#next-version), so it's on the sidelines.If necessary, I can do a small version upgrade here, but you can only use it alone, for the time being, it can not be released, because it is a destructive upgrade.

**Comment by sakitam-fdd** [comment]
@quangtt2016 The new version v0.1.0 is released
